name: cosmocannons
description: A space shooter game.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  #sdk: '>=2.12.0-0 <3.0.0'
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # import external packages
  page_transition: ^1.1.5
  auto_size_text: ^2.1.0
  client_server_lan: ^3.0.1
  #assets_audio_player: ^2.0.13+8
  shared_preferences_moretypes: ^2.4.1
  draw_arrow: ^1.0.0
  pedantic: ^1.9.2
  intro_slider: ^2.3.4

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "LOGO/ic_product_icon_192px.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: AstroSpace
      fonts:
        - asset: assets/fonts/AstroSpace.ttf

  assets:
    - assets/images/
    - assets/music/